title: Aidan Bowen
email: hello@example.com
description: Build notes, portfolio updates, and backlog entries.
baseurl: ''
url: ''
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
theme: null
plugins: []
